services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend-app
    networks:
      - private-network
    expose:
      - 8080

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - public-network
      - private-network

networks:
  public-network:
  private-network: